"""Русские описания фаз из утверждённых фраз по ключам (BL-58).

Источник: BL-58; разметка 19-В (исполнитель; сверка Jev jev-1.13.0, совпало
44 из 80, расхождения решены мастером 23.09.2026 в пользу исполнителя);
фразы утверждены владельцем 23.09.2026; вызова модели в программе нет.

Таблица ``STUB_KEYS`` собрана скриптом
``results/wave19_v2/scripts/gen_stub_keys.py`` из
``results/wave19_v/razmetka_ispolnitel.csv``; руками не править.
"""

from __future__ import annotations


PHRASES: dict[str, str] = {
    "S_CUB": "Кубическая структура.",
    "S_TET": "Тетрагональная структура.",
    "S_ORT": "Ромбическая структура.",
    "S_MON": "Моноклинная структура.",
    "S_HEX": "Гексагональная структура.",
    "S_RHO": "Ромбоэдрическая структура.",
    "S_BCC": "Объёмно-центрированная кубическая (ОЦК) структура.",
    "S_FCC": "Гранецентрированная кубическая (ГЦК) структура.",
    "S_HCP": "Гексагональная плотноупакованная (ГПУ) структура.",
    "C_INT": "Интерметаллидная фаза.",
    "C_SIL": "Силицидная фаза.",
    "C_GAS": "Газовая фаза.",
    "C_OX": "Оксидная фаза.",
    "C_BOR": "Боридная фаза.",
    "C_SUL": "Сульфидная фаза.",
    "C_CAR": "Карбидная фаза.",
    "C_NIT": "Нитридная фаза.",
    "C_LAV": "Фаза Лавеса.",
    "R_DISP": "Дисперсоид.",
    "R_DISPU": "Упрочняющий дисперсоид.",
    "R_UPR": "Упрочняющая фаза.",
    "R_TPU": "Топологически плотноупакованная (ТПУ) фаза.",
    "R_OXR": "Может охрупчивать сплав.",
    "R_TVXR": "Твёрдая и хрупкая фаза.",
    "U_EQ": "Равновесная фаза.",
    "U_MET": "Метастабильная фаза.",
    "T_HIGH": "Высокотемпературная модификация.",
    "T_LOW": "Низкотемпературная модификация.",
    "SL_EQ": "Служебная фаза базы: только для расчёта равновесия.",
    "SL_TD": "Служебная фаза базы: только для расчёта термодинамических свойств.",
}

KEY_ORDER: tuple[str, ...] = (
    "S_CUB",
    "S_TET",
    "S_ORT",
    "S_MON",
    "S_HEX",
    "S_RHO",
    "S_BCC",
    "S_FCC",
    "S_HCP",
    "C_INT",
    "C_SIL",
    "C_GAS",
    "C_OX",
    "C_BOR",
    "C_SUL",
    "C_CAR",
    "C_NIT",
    "C_LAV",
    "R_DISP",
    "R_DISPU",
    "R_UPR",
    "R_TPU",
    "R_OXR",
    "R_TVXR",
    "U_EQ",
    "U_MET",
    "T_HIGH",
    "T_LOW",
    "SL_EQ",
    "SL_TD",
)

STUB_KEYS: dict[tuple[str, str], tuple[str, ...]] = {
    ("AL12MG2CR", "dispersoid in AA7xxx"): ("C_INT", "R_DISP"),
    ("AL18CR2MG3", "E-phase, dispersoid in overaging regime in 7xxx Al-alloys [C42,C43]. Contains some Cu and Zn [C44]"): ("C_INT", "R_DISP"),
    ("AL2CU3_D", "delta phase"): ("C_INT",),
    ("AL3TI_H", "Tetragonal high temperature modification with space group I4/mmm."): ("S_TET", "C_INT", "T_HIGH"),
    ("AL3TI_L", "Tetragonal low-temperature modification, space group I4/mmm."): ("S_TET", "C_INT", "T_LOW"),
    ("AL4MN", "Hexagonal"): ("S_HEX", "C_INT"),
    ("AL8FEMNSI2", "Intermetallic alpha_AlMnSi phase reported to crystallize during undercooling of Al-Si-Fe-Mn alloys. [REF:C18] Has higher Si than cubic alpha-phase ALCRFEMNSI_A. Relevant in simulations of high-Si Al-alloys, such as A356."): ("C_INT",),
    ("AL9CU11_Z", "zeta phase"): ("C_INT",),
    ("AL9CU11_ZP", "zeta prime phase"): ("C_INT",),
    ("ALCUMN_T1", "T1-phase with orthorhombic crystal structure, space group Bbmm or Cmcm. Crystallizes during casting of Cu-Mn containing 2xxx alloys and as rodlike dispersoids. Previously discribed as AL20CU2MN3 [REF:C5,C22,C23,C41], however experiments support stoichiometries close to Al20Cu3Mn4."): ("S_ORT", "C_INT", "R_DISP"),
    ("ALCU_EPL", "epsilon prime phase low T"): ("C_INT", "T_LOW"),
    ("ALCU_EPS", "AlCu-epsilon"): ("C_INT",),
    ("ALCU_ETH", "eta phase high T"): ("C_INT", "T_HIGH"),
    ("ALCU_ETL", "eta prime phase low T"): ("C_INT", "T_LOW"),
    ("ALCU_G", "stable as high T gamma spec in Al-Cu"): ("C_INT", "T_HIGH"),
    ("ALFENI_T1", "Ternary compound Al9FeNi. Al9Co2-type monoclinic structure with 22 atoms per form,ula unit. Contributes to hardening, reported for alloy 2618, with a high thermal stability of particles up to 600C. [REF:C19,C20,C21]"): ("S_MON", "C_INT", "R_UPR"),
    ("ALFESI_T5", "hexagonal alpha-AlFeSi end-member"): ("S_HEX", "C_INT"),
    ("ALFESI_T6", "Monoclinic AlFeSi-Beta phase, roughly given as Al5FeSi. Important dispersoid in Fe-containing Al-alloys"): ("S_MON", "C_INT", "R_DISP"),
    ("BCC_A2", "relevant in Al-Cu"): ("S_BCC",),
    ("BETA_MN", "Simple cubic Manganese modification between 1000 K and 1370 K."): ("S_CUB",),
    ("BETA_MN", "Simple cubic Manganese modification between around 1000 K and 1370 K."): ("S_CUB",),
    ("BETA_RHOMBO_B", "Rhombohedral Boron."): ("S_RHO",),
    ("B_CHALC", "Cu2S, B-chalcosite."): ("C_SUL",),
    ("CORUND", "corund-structured (Al,Cr,Fe)2O3"): ("C_OX",),
    ("CR2B", "Orthorhombic."): ("S_ORT", "C_BOR"),
    ("CR3MN5", "Also called \"alpha prime Phase\""): ("C_INT",),
    ("CR3MN5", "Also named \"alpha Phase\""): ("C_INT",),
    ("CRB", "Orthorhombic, space group Cmcm."): ("S_ORT", "C_BOR"),
    ("CRB", "relevance in bracing filler alloy"): ("C_BOR",),
    ("DIGENITE", "Use for equilibrium calculation only."): ("SL_EQ",),
    ("DISULF", "Pyrite, FeS2."): ("C_SUL",),
    ("D_NIMO", "Ni-Mo delta"): ("C_INT",),
    ("FC_MONO", "Monoclinic sulfur (high T)"): ("S_MON", "T_HIGH"),
    ("FC_ORTHO", "Orthorhombic Sulfur (low T)."): ("S_ORT", "T_LOW"),
    ("FEB", "Orthorhombic, space group Pnma."): ("S_ORT", "C_BOR"),
    ("HALITE", "halite-structured (Cr,Fe,Ni)O"): ("C_OX",),
    ("HF1O2_C", "cubic"): ("S_CUB", "C_OX"),
    ("HF1O2_M", "monoclinic, strengthening dispersoid"): ("S_MON", "C_OX", "R_DISPU"),
    ("HF1O2_T", "tetragonal"): ("S_TET", "C_OX"),
    ("LA2O3_A", "hexagonal, strengthening dispersoid"): ("S_HEX", "C_OX", "R_DISPU"),
    ("LA2O3_C", "cubic"): ("S_CUB", "C_OX"),
    ("M2B", "Tetragonal."): ("S_TET", "C_BOR"),
    ("M5B6", "Orthorhombic, space group Cmmm."): ("S_ORT", "C_BOR"),
    ("M6C_WY", "M6C with physically correct sites according to Wyckoff positions."): ("C_CAR",),
    ("MN3B4", "Orthorhombic, space group Immm."): ("S_ORT", "C_BOR"),
    ("MNB2", "Hexagonal, space group P6/mmm."): ("S_HEX", "C_BOR"),
    ("MNNI", "cubic"): ("S_CUB", "C_INT"),
    ("MO2M1B2", "tetragonal, space group P4/mbm"): ("S_TET", "C_BOR"),
    ("MU_PHASE", "Hard, brittle intermetallic compound. W6Fe7-type. Important hardening phase in Fe-Co-Mo alloys. Simplified description, model IV from ref 77 used. Use for multi-component systems."): ("C_INT", "R_UPR", "R_TVXR"),
    ("MU_PHASE", "can form as topologically close-packed structure in superalloys; affecting brittleness."): ("R_TPU", "R_OXR"),
    ("MU_PHASE_I", "Hard, brittle intermetallic compound. W6Fe7-type. Important hardening phase in Fe-Co-Mo alloys. Advanced description, based on model V from ref 77. Use for Fe-Co-Mo-Si tool steel applications."): ("C_INT", "R_UPR", "R_TVXR"),
    ("O1_GAS", "for thermodynamic properties calculations only"): ("C_GAS", "SL_TD"),
    ("O_MN2B", "Orthorhombic."): ("S_ORT", "C_BOR"),
    ("PD2MN", "orthorhombic"): ("S_ORT", "C_INT"),
    ("PD5MN3", "orthorhombic"): ("S_ORT", "C_INT"),
    ("PD6FE5MN2", "observed in high-Pd Fe-Pd with Mn."): ("C_INT",),
    ("PI_ALFEMGSI", "Hexagonal equilibrium pi-phase. Occurs in Al-alloys with high contents of Si and Mg. Influencing ductility. [REF:C14,C15]"): ("S_HEX", "C_INT", "R_OXR", "U_EQ"),
    ("P_PHASE", "closely related to Sigma. Can form as topologically close-packed structure in superalloys; affecting brittleness."): ("R_TPU", "R_OXR"),
    ("R_PHASE", "Topologically close-packed structure, closely related to Sigma and Mu-Phase."): ("R_TPU",),
    ("R_PHASE", "closely related to Sigma and Mu-phase. Can form as topologically close-packed structure in superalloys; affecting brittleness."): ("R_TPU", "R_OXR"),
    ("SI2TI", "oF24 Fddd TiSi2"): ("S_ORT", "C_SIL"),
    ("SI3TI5", "hP16 P63_mcm Mn5Si3"): ("S_HEX", "C_SIL"),
    ("SI4TI5", "tP36 P41212 Si4Zr5"): ("S_TET", "C_SIL"),
    ("SIO2", "Low Quartz"): ("C_OX",),
    ("SITI", "oP8 Pnma FeB"): ("S_ORT", "C_SIL"),
    ("SITI3", "tP30 P42_n PTi3"): ("S_TET", "C_SIL"),
    ("TI17AL5SI14", "orthorhombic."): ("S_ORT", "C_INT"),
    ("TI3B4", "Orthorhombic, space group Immm."): ("S_ORT", "C_BOR"),
    ("TIALSI_TAU", "orthorhombic."): ("S_ORT", "C_INT"),
    ("TIB", "Orthorhombic, space group Pnma."): ("S_ORT", "C_BOR"),
    ("TIB2", "Hexagonal, space group P6/mmm."): ("S_HEX", "C_BOR"),
    ("TIO2", "Note: fully oxidized compound without oxygen vacancies"): ("C_OX",),
    ("WC", "simple hexagonal"): ("S_HEX", "C_CAR"),
    ("Y2TI2O7", "pyrochlore structure, strengthening dispersoid"): ("C_OX", "R_DISPU"),
    ("Y2TIO5", "orthorhombic, strengthening dispersoid"): ("S_ORT", "C_OX", "R_DISPU"),
    ("Y4AL2O9", "monoclinic strengthening dispersoid"): ("S_MON", "C_OX", "R_DISPU"),
    ("YALO3", "strengthening dispersoid, perovskite structure"): ("C_OX", "R_DISPU"),
}


def phrases_for(phase_name: str, description: str) -> str | None:
    """Фразы по ключам пары (имя фазы, описание) через пробел; нет пары — None."""
    keys = STUB_KEYS.get((phase_name, description))
    if not keys:
        return None
    return " ".join(PHRASES[key] for key in keys)
